- name: Copy file to the remote server
  hosts: "{{ variable_host | default('web') }}"
  gather_facts: false
  tasks:
  - name: Create directory
    file:
     name: /home/ysurmd/ansible/squad
     state: directory
     owner: ysurmd
     mode: 0755

  - name: Copy file to the remote server
    copy:
      src: "{{ item }}"
      dest: /home/ysurmd/ansible/squad/
      owner: ysurmd
      mode: 0755
    with_items:
       - /home/ysurmd/ansible/squad/set_password_policy.sh
       - /home/ysurmd/ansible/squad/user.txt

- name: Set password policy
  hosts: "{{ variable_host | default('web') }}"
  gather_facts: false
  become: yes
  tasks:
  - name: Set password maxage 90
    shell: /home/ysurmd/ansible/squad/set_password_policy.sh
