- name: Check the CHEF Server
  shell: cat /etc/chef/knife.rb | grep chef_server_url | sed 's/[ ][ ]*/,/g' | awk -F "," '{print $2}' | awk -F / '{print $3}'
  register: result

- name: Debug
  debug:
    msg: "{{ result.stdout_lines }}"
  
#- name: Check CHEF Server HOST IP port 443
